#include "addressing.h"
#include "flags.h"
#include "instructions.h"
#include "opcodes.h"

const Opcode opcode_table[256] = {
  [0x00] = { .execute = brk, .address = addr_implied, .cycles = 7, .page_cross_penalty = 0 },
  [0x18] = { .execute = clc, .address = addr_implied, .cycles = 2, .page_cross_penalty = 0 },
  [0x38] = { .execute = sec, .address = addr_implied, .cycles = 2, .page_cross_penalty = 0 },
  [0x40] = { .execute = rti, .address = addr_implied, .cycles = 6, .page_cross_penalty = 0 },
  [0x58] = { .execute = cli, .address = addr_implied, .cycles = 2, .page_cross_penalty = 0 },
  [0x78] = { .execute = sei, .address = addr_implied, .cycles = 2, .page_cross_penalty = 0 },
  [0x81] = { .execute = sta, .address = addr_indirect_x, .cycles = 6, .page_cross_penalty = 0 },
  [0x84] = { .execute = sty, .address = addr_zero_page, .cycles = 3, .page_cross_penalty = 0 },
  [0x85] = { .execute = sta, .address = addr_zero_page, .cycles = 3, .page_cross_penalty = 0 },
  [0x86] = { .execute = stx, .address = addr_zero_page, .cycles = 3, .page_cross_penalty = 0 },
  [0x8A] = { .execute = txa, .address = addr_implied, .cycles = 2, .page_cross_penalty = 0 },
  [0x8C] = { .execute = sty, .address = addr_abs, .cycles = 4, .page_cross_penalty = 0 },
  [0x8D] = { .execute = sta, .address = addr_abs, .cycles = 4, .page_cross_penalty = 0 },
  [0x8E] = { .execute = stx, .address = addr_abs, .cycles = 4, .page_cross_penalty = 0 },
  [0x91] = { .execute = sta, .address = addr_indirect_y, .cycles = 6, .page_cross_penalty = 0 },
  [0x94] = { .execute = sty, .address = addr_zero_page_x, .cycles = 4, .page_cross_penalty = 0 },
  [0x95] = { .execute = sta, .address = addr_zero_page_x, .cycles = 4, .page_cross_penalty = 0 },
  [0x96] = { .execute = stx, .address = addr_zero_page_y, .cycles = 4, .page_cross_penalty = 0 },
  [0x98] = { .execute = tya, .address = addr_implied, .cycles = 2, .page_cross_penalty = 0 },
  [0x99] = { .execute = sta, .address = addr_abs_y, .cycles = 5, .page_cross_penalty = 0 },
  [0x9D] = { .execute = sta, .address = addr_abs_x, .cycles = 5, .page_cross_penalty = 0 },
  [0xA0] = { .execute = ldy, .address = addr_imm, .cycles = 2, .page_cross_penalty = 0 },
  [0xA1] = { .execute = lda, .address = addr_indirect_x, .cycles = 6, .page_cross_penalty = 0 },
  [0xA2] = { .execute = ldx, .address = addr_imm, .cycles = 2, .page_cross_penalty = 0 },
  [0xA4] = { .execute = ldy, .address = addr_zero_page, .cycles = 3, .page_cross_penalty = 0 },
  [0xA5] = { .execute = lda, .address = addr_zero_page, .cycles = 3, .page_cross_penalty = 0 },
  [0xA6] = { .execute = ldx, .address = addr_zero_page, .cycles = 3, .page_cross_penalty = 0 },
  [0xA8] = { .execute = tay, .address = addr_implied, .cycles = 2, .page_cross_penalty = 0 },
  [0xA9] = { .execute = lda, .address = addr_imm, .cycles = 2, .page_cross_penalty = 0 },
  [0xAA] = { .execute = tax, .address = addr_implied, .cycles = 2, .page_cross_penalty = 0 },
  [0xAC] = { .execute = ldy, .address = addr_abs, .cycles = 4, .page_cross_penalty = 0 },
  [0xAD] = { .execute = lda, .address = addr_abs, .cycles = 4, .page_cross_penalty = 0 },
  [0xAE] = { .execute = ldx, .address = addr_abs, .cycles = 4, .page_cross_penalty = 0 },
  [0xB1] = { .execute = lda, .address = addr_indirect_y, .cycles = 5, .page_cross_penalty = 0 },
  [0xB4] = { .execute = ldy, .address = addr_zero_page_x, .cycles = 4, .page_cross_penalty = 0 },
  [0xB5] = { .execute = lda, .address = addr_zero_page_x, .cycles = 4, .page_cross_penalty = 0 },
  [0xB6] = { .execute = ldx, .address = addr_zero_page_y, .cycles = 4, .page_cross_penalty = 0 },
  [0xB8] = { .execute = clv, .address = addr_implied, .cycles = 2, .page_cross_penalty = 0 },
  [0xB9] = { .execute = lda, .address = addr_abs_y, .cycles = 3, .page_cross_penalty = 1 },
  [0xBC] = { .execute = ldy, .address = addr_abs_x, .cycles = 4, .page_cross_penalty = 1 },
  [0xBD] = { .execute = lda, .address = addr_abs_x, .cycles = 4, .page_cross_penalty = 1 },
  [0xBE] = { .execute = ldx, .address = addr_abs_y, .cycles = 3, .page_cross_penalty = 1 },
  [0xD8] = { .execute = cld, .address = addr_implied, .cycles = 2, .page_cross_penalty = 0 },
  [0xEA] = { .execute = nop, .address = addr_implied, .cycles = 2, .page_cross_penalty = 0 },
  [0xF8] = { .execute = sed, .address = addr_implied, .cycles = 2, .page_cross_penalty = 0 },
};